config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("wishlists/", include("wishlists.urls", namespace="wishlists")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_mentor", views.search_mentor, name="search_mentor"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("create/<int:mentor>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("list/", views.ReservationListView.as_view(), name="list"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
namespace = "users"
urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),  # login을 위한 url
    path("logout", views.log_out, name="logout"),  # logout을 위한 url
    path("signup", views.SignUpView.as_view(), name="signup"),  # signup를 위한 url
    path(
        "socialsignup", views.SocialSignUpView.as_view(), name="socialsignup"
    ),  # social signup을 위한 url
    path(
        "verify/<str:key>", views.complete_verification, name="complete-verification"
    ),  # 이메일 인증을 위한 url
    path("Mentor/<int:pk>/", views.MentorDetail.as_view(), name="detail"),
    path(
        "Mentor-profile/<int:pk>/",
        views.MentorProfileView.as_view(),
        name="mentor-profile",
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "update-mentor-profile/",
        views.UpdateMentorProfileView.as_view(),
        name="mentor-update",
    ),
    path("point/", views.UserPointView.as_view(), name="point"),
    path("point/add/", views.ajax_buy_point, name="buy_point"),
    path(
        "update-mentor-profile/",
        views.UpdateMentorProfileView.as_view(),
        name="mentor-update",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path(
        "sms_verfy/",
        views.ajax_sms_verfy,
        name="sms_verfy",
    ),
    path(
        "sms_check/",
        views.ajax_sms_check,
        name="sms_check",
    ),
    path("Mentorsignup/", views.MentorSignUpView.as_view(), name="Mentorsignup"),
    path("Mentorsignup/kakaomap", views.renderkakaomap),
    path("Mentor-list/", views.MentorListView.as_view(), name="MentorList"),
    path("manage/", views.ManageUserView.as_view(), name="manage"),
    path("manage/submit", views.manage_user, name="submit"),
    path("kakao/login/callback/", views.kakao_callback, name="kakao-callback"),
    path("kakao/signup", views.KakaoSignUpView.as_view(), name="kakaosignup"),
    path("kakaologin",views.KakaoLoginTest.as_view(), name = "kakaologin"),
]

wishlists/urls.py
from django.urls import path
from . import views
app_name = "wishlists"

urlpatterns = [
    path("toggle/<int:mentor_pk>/", views.toggle_mentor , name="toggle-mentor"),
    path("favs/", views.SeeFavsView.as_view() , name="see-favs")
]

templates/partials/footer.html
{% load static %}
<footer class="wrkxek text-gray-600 body-font">
  <div class="container px-5 py-4 mx-auto flex items-center sm:flex-row flex-col">
  <a href="{% url 'core:home' %}">
        <img class="w-32 h-24 py-8 pt-6 pb-4 bg-cover bg-center" src="{% static 'img/logo1.png' %}" />
  </a>
    <p class="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4">© 2021 Mentors —
      <a class="text-gray-600 ml-1" rel="noopener noreferrer" target="_blank">@조강정허</a>
    </p>
    <span class="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
      <a class="text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
          <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
          <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
        </svg>
      </a>
      <a class="ml-3 text-gray-500">
        <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
          <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
          <circle cx="4" cy="4" r="2" stroke="none"></circle>
        </svg>
      </a>
    </span>
  </div>
</footer>

templates/partials/nav.html
{% load static %}
{% comment %} <header class="container max-w-full flex items-center justify-between h-20 border-b border-gray-400"> {% endcomment %}
<div class="flex w-full z-30 fixed">
  <div @click.away="open = false"
    class="flex flex-col md:flex-row w-full text-gray-700 bg-white flex-shrink-0 shadow-md border rounded-b-lg"
    x-data="{ open: false }">
    <div class="flex-shrink-0 px-8 py-2 flex flex-row items-center justify-between">

      <a href="{% url 'core:home' %}">
        <img class="w-32 h-24 py-8 pt-6 pb-4 bg-cover bg-center" src="{% static 'img/logo1.png' %}" />
      </a>

      <button
        class="rounded-lg md:hidden focus:outline-none focus:shadow-outline h-12 w-12 flex justify-center items-center"
        @click="open = !open">
        <svg fill="currentColor" viewBox="0 0 20 20" class="w-8 h-8">
          <path x-show="!open" fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM9 15a1 1 0 011-1h6a1 1 0 110 2h-6a1 1 0 01-1-1z"
            clip-rule="evenodd"></path>
          <path x-show="open" fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"></path>
        </svg>
      </button>

    </div>

    <nav :class="{'block': open, 'hidden': !open}"
      class="flex-grow px-4 md:px-0 md:pr-4 pb-4 md:pb-0 md:flex md:flex-row md:justify-between md:items-center">
            
      <form id="search" method="GET" action="{% url 'core:search_mentor' %}" class="w-full flex md:hidden">
      {% csrf_token %}
        <div class="flex flex-row px-4 py-2 mt-2 text-sm font-semibold text-gray-600 bg-gray-200 rounded-lg w-full">
          <input class="bg-gray-200 focus:outline-none flex-1" placeholder="Search" type="search" name="search" aria-label="name" value="{{name}}">
          <button type= "submit"
            class="flex items-center justify-center text-sm font-semibold bg-gray-300 h-6 px-2 rounded-full ml-auto focus:outline-none">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </form> 
      
      
      <div class="relative md:flex md:flex-row md:items-center z-10 md:border-l-2 md:pl-4 md:space-x-2">
        <!-- Mentor List -->
        <a href="{% url 'users:MentorList' %}"
          class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
          <span class="uppercase">Mentors</span>
        </a>
        <!-- Mentor List -->
        {% if user.is_authenticated %}        
        <!-- Favs -->
          <a href="{% url 'wishlists:see-favs' %}"
            class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
            <span class="uppercase">Favs</span>
          </a>
        <!-- Favs -->

        <!-- Reservation -->
          <a href="{% url 'reservations:list' %}"
            class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
            <span class="uppercase">Reservation</span>
          </a>
        <!-- Reservation -->

        <!-- UserProfile -->        
          <a href="{% url 'users:profile' user.pk %}"
            class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
            <span class="uppercase">Profile</span>
          </a>        
        <!-- Mentorsignup -->        
        {% if user.is_mentor %}
        {% else%}
        <a href="{% url 'users:Mentorsignup' %}"
          class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
          <span class="uppercase">Mentorsignup</span>
        </a>
        {% endif%}
        {% endif %}

        <!-- Mentor manage -->
        {% if user.is_authenticated and user.is_superuser %}
        <a href="{% url 'users:manage' %}"
          class="duration-300 w-full flex px-4 py-2 mt-2 md:mt-0 text-sm font-semibold text-left rounded-lg hover:text-indigo-500 hover:bg-gray-200">
          <span class="uppercase">Mentor manage</span>
        </a>
        {% endif %}
        <!-- Admin -->
      </div>

      <!-- Search -->
      <form :class="{'block': !open, 'hidden': open}"
        class="form-inline my-2 my-lg-0" action="{% url 'core:search_mentor' %}" method="post">
        {% csrf_token %}
        <input class="serchh form-control mr-sm-2 h-10" type="search" placeholder="Search" aria-label="Search" name="name" value="{{name}}">
        <button class="btn bg-gray-500 h-10 w-16 rounded-lg text-white btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
      </form>
      <!-- Search -->

      <!--Login, Logout-->
      <div class="relative md:ml-10 md:w-32 z-0">
        {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}"
          class="mt-2 md:mt-0 bg-red-500 shadow-md text-white flex justify-center duration-300 uppercase px-4 py-2 text-sm font-semibold bg-transparent rounded-lg hover:bg-red-700 focus:bg-red-700 focus:outline-none focus:shadow-outline">
          <svg fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"
            stroke="currentColor" class="h-5 w-5">
            <path d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z">
            </path>
          </svg>
          <span class="ml-2">Logout</span>
        </a>
        {% else %}
        <a href="{% url 'users:login' %}"
          class="mt-2 md:mt-0 bg-green-500 shadow-md text-white flex justify-center duration-300 uppercase px-4 py-2 text-sm font-semibold bg-transparent rounded-lg hover:bg-green-700 focus:bg-green-700 focus:outline-none focus:shadow-outline">
          <svg fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"
            stroke="currentColor" class="h-5 w-5">
            <path d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z">
            </path>
          </svg>
          <span class="ml-2">Login</span>
        </a>
        {% endif %}
      </div>
      <!--Login, Logout-->
    </nav>
  </div>
</div>
{% comment %} </header> {% endcomment %}