config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("wishlists/", include("wishlists.urls", namespace="wishlists")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views
app_name="conversations"

urlpatterns = [
    path("go/<int:user_pk>/<int:mentor_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
    path("list/<int:pk>/", views.MessageListView.as_view(), name="list"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_mentor", views.search_mentor, name="search_mentor"),
]

conversations/models.py
from django.db import models
from core import models as core_models

# Create your models here.
class Conversation(core_models.TimeStampedModel):
    user = models.ForeignKey("users.User", related_name="conversations", on_delete=models.CASCADE)
    mentor = models.ForeignKey("users.Mentor", related_name="conversations", on_delete=models.CASCADE)
    
    
    def count_messages(self):
        return self.messages.count()
    count_messages.short_description = "Number of Messages"
    

class Message(core_models.TimeStampedModel):
    conversation = models.ForeignKey("conversations.Conversation", related_name="messages", on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", related_name="messages", on_delete=models.CASCADE)
    message = models.TextField()

conversations/forms.py
from django import forms

class AddCommentForm(forms.Form):
    message = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': "Add a Comment"}))

conversations/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.views.generic import View, ListView
from users import models as user_models
from . import models, forms
# Create your views here.


def go_conversation(requset, user_pk, mentor_pk):
    user = user_models.User.objects.get(pk=user_pk)
    mentor = user_models.Mentor.objects.get(pk=mentor_pk)
    if user is not None and mentor is not None:
        try:
            conversation = models.Conversation.objects.get(Q(user=user) & Q(mentor=mentor))
        except models.Conversation.DoesNotExist:
            conversation = models.Conversation.objects.create(
                user = user,
                mentor = mentor,
            )
        return redirect(reverse("conversations:detail", kwargs={'pk':conversation.pk}))
    
class ConversationDetailView(View):
    
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        conversation = models.Conversation.objects.get(pk=pk)
        if not conversation:
            raise Http404()
        return render(self.request, "conversations/conversation_detail.html", {"conversation":conversation})
    
    def post(self, *args, **kwargs):
        message = self.request.POST.get('message', None)
        pk = kwargs.get("pk")
        conversation = models.Conversation.objects.get(pk=pk)
        if not conversation:
            raise Http404()
        if message is not None:
            models.Message.objects.create(
                message=message,
                user=self.request.user,
                conversation=conversation
            )
        return redirect(reverse("conversations:detail", kwargs={'pk':pk}))
        
class MessageListView(ListView):
    model = models.Message
    context_object_name = "Messages"
    template_name = "conversations/message_list.html"
    ordering = "created"
    
    def get_queryset(self):
        pk = self.kwargs.get("pk")
        return models.Message.objects.filter(conversation_id=pk).order_by("created")

templates/conversations/conversation_detail.html
{% extends "base.html" %}

{% block page_title %}
    Conversation
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 mt-32 flex justify-between min-h-50vh">

        <div class="border w-1/4 p-10">
            <span class="text-center w-full block text-lg font-medium">Conversation between:</span>
            <div class="flex justify-between mt-10 items-center">

                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=conversation.user.name %}
                    <span class="mt-2 text-gray-500">{{conversation.user.name}}</span>
                </div>

                <span class="font-medium text-2xl">&</span>

                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=conversation.mentor.user.name %}
                    <span class="mt-2 text-gray-500">{{conversation.mentor.user.name}}</span>
                </div>
            </div>
        </div>
        <div class="flex-grow ">
            <div class="border ml-10 p-10 flex flex-col">
                {% if conversation.messages.count == 0 %}
                    no messages
                {% else %}
                    {% comment %} {% for message in conversation.messages.all  %}
                        <div class="mb-10 {% if message.user.pk == user.pk %} self-end text-right {% endif %}">
                            <span class="text-sm font-medium text-gray-600">{{message.user.first_name}}</span>
                            <div class="mt-px p-5 w-56 rounded {% if message.user.pk != user.pk %}bg-teal-500 text-white{% else %}bg-gray-300{% endif %}">
                                {{message.message}}
                            </div>
                        </div>
                    {% endfor %} {% endcomment %}
                    <iframe src="{% url 'conversations:list' conversation.pk %}" class="w-full h-screen"></iframe>
                {% endif %}
            </div>
            <form class="mt-10 w-1/2 mx-auto" method="POST">
                {% csrf_token %}
                <input class="border-box mb-5" name="message" placeholder="Wirte a Message" required />
                <button class="btn-link">Send Comment</button>
            </form>
        </div>

    </div>
{% endblock content %} 

templates/conversations/message_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="relative min-h-full m-0 display-none">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" , href="{% static "css/styles.css" %}">
</head>

<body>
<div id="bodyContents" class="flex flex-col h-screen py-2">
    {% for message in Messages  %}
        <div class="mb-10 {% if message.user.pk == user.pk %} self-end text-right {% endif %}">
            <span class="text-sm font-medium text-gray-600">{{message.user.first_name}}</span>
            <div class="mt-px p-5 w-56 rounded {% if message.user.pk != user.pk %}bg-teal-500 text-white{% else %}bg-gray-300{% endif %}">
                {{message.message}}
            </div>
        </div>
    {% endfor %}
</div>
</body>

</html>

<script>
setTimeout(function() {
    acyncMovePage(document.location.href);
}, 1000);
</script>

<script>
    function acyncMovePage(url){
        // ajax option
        var ajaxOption = {
                url : url,
                async : true,
                type : "GET",
                dataType : "html",
                cache : false
        };

        $.ajax(ajaxOption).done(function(data){
            // Contents 영역 삭제
            $('#bodyContents').children().remove();
            // Contents 영역 교체
            $('#bodyContents').html(data);
        });
    }
</script>