config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("wishlists/", include("wishlists.urls", namespace="wishlists")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversations/urls.py
from django.urls import path
from . import views
app_name="conversations"

urlpatterns = [
    path("go/<int:user_pk>/<int:mentor_pk>/", views.go_conversation, name="go"),
    path("<int:pk>/", views.ConversationDetailView.as_view(), name="detail"),
    path("list/<int:pk>/", views.MessageListView.as_view(), name="list"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_mentor", views.search_mentor, name="search_mentor"),
]

reservations/urls.py
from django.urls import path
from . import views

app_name = "reservations"

urlpatterns = [
    path("create/<int:mentor>/<int:year>-<int:month>-<int:day>/", views.create, name="create"),
    path("<int:pk>/", views.ReservationDetailView.as_view(), name="detail"),
    path("<int:pk>/<str:verb>/", views.edit_reservation, name="edit"),
    path("list/", views.ReservationListView.as_view(), name="list"),
]

reservations/models.py
import datetime
from django.db import models
from django.utils import timezone
from core import models as core_models

# Create your models here.

class BookedTime(core_models.TimeStampedModel):
    time = models.DateField()
    reservation = models.ForeignKey("reservation", on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Booked Time"
        verbose_name_plural = "Booked Times"
        
    def __str__(self):
        return str(self.day)

class BookedDay(core_models.TimeStampedModel):
    day = models.DateField()
    reservation = models.ForeignKey("reservation", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Booked Day"
        verbose_name_plural = "Booked Days"
        
    def __str__(self):
        return str(self.day)

class Reservation(core_models.TimeStampedModel):
    
    STATUS_PENDING = "pending"
    STATUS_CONFIRMED = "confirmed"
    STATUS_CANCELED = "canceled"
    STATUS_CHOICES = (
        (STATUS_PENDING, "Pending"),
        (STATUS_CONFIRMED, "Confirmed"),
        (STATUS_CANCELED, "Canceled")
    )
    
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default=STATUS_PENDING)
    user = models.ForeignKey("users.User", related_name="reservations", on_delete=models.CASCADE)
    mentor = models.ForeignKey("users.Mentor", related_name="reservations", on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()
    is_confirmed = models.BooleanField(default=False)
    
    def menteename(self):
        return self.user.name
    
    def mentorname(self):
        return self.mentor.user.name
    
    def in_progress(self):
        now = timezone.now().date()
        return now >= self.check_in and now <= self.check_out
    in_progress.boolean = True
    
    def is_finished(self):
        now = timezone.now().date()
        is_finished = now > self.check_out
        if is_finished:
            BookedDay.objects.filter(reservation=self).delete()
        return is_finished
    is_finished.boolean = True
    
    def save(self, *args, **kwargs):
        if self.pk is None:
            start = self.check_in
            end = self.check_out
            difference = end - start
            existing_booked_day = BookedDay.objects.filter(day__range=(start, end)).exists()
            if not existing_booked_day:
                super().save(*args, **kwargs)
                for i in range(difference.days):
                    day = start + datetime.timedelta(days=i)
                    BookedDay.objects.create(day=day, reservation=self)
                return
        return super().save(*args, **kwargs)
    
    def count_reservations(self):
        return self.reservations.count()
    count_reservations.short_description = "Number of Reservations"

reservations/views.py
import datetime
from django.http import Http404
from django.views.generic import View, ListView
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from users import models as user_models
from reviews import forms as reviews_forms
from django.core.paginator import Paginator
from django.db.models import Q
from . import models

# Create your views here.

class CreateError(Exception):
    pass

def create(request, mentor, year, month, day):
    try:
        date_obj = datetime.datetime(year, month, day)
        mentor = user_models.Mentor.objects.get(pk=mentor)
        models.BookedDay.objects.get(day=date_obj, reservation__mentor=mentor)
        raise CreateError()
    except (user_models.Mentor.DoesNotExist, CreateError):
        messages.error(request, "Can't Reserve That Mentor")
        return redirect(reverse("core:home"))
    except models.BookedDay.DoesNotExist:
        user = request.user
        ckr = models.Reservation.objects.get_or_none(
            user=user,
            mentor=mentor,
            check_in=date_obj,
        )
        if ckr is None:
            user.point = user.point - 20
            mentor.user.point = mentor.user.point + 20
            user.save()
            mentor.user.save()
            reservation = models.Reservation.objects.create(
                user=user,
                mentor=mentor,
                check_in=date_obj,
                check_out=date_obj,
            )
            return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))
        return redirect(reverse("reservations:detail", kwargs={"pk": ckr.pk}))
class ReservationDetailView(View):
    
    def get(self, *args, **kwargs):
        pk = kwargs.get("pk")
        user = self.request.user
        reservation = models.Reservation.objects.get_or_none(pk=pk)
        if reservation is None or (not (reservation.user == user or reservation.mentor.user == user)):
            return redirect(reverse("core:home"))
        form = reviews_forms.CreateReviewForm()
        return render(self.request, "reservations/detail.html", {"reservation":reservation, "form":form})

def edit_reservation(request, pk, verb):
    reservation = models.Reservation.objects.get_or_none(pk=pk)
    # if reservation is None or (reservation.user != request.user or reservation.mentor.user != request.user):
    #    raise Http404()
    if verb == "confirm":
        reservation.status = models.Reservation.STATUS_CONFIRMED
        reservation.is_confirmed = True
    elif verb == "cancel":
        reservation.status = models.Reservation.STATUS_CANCELED
        user = request.user
        mentor = reservation.mentor
        user.point = user.point + 20
        mentor.user.point = mentor.user.point - 20
        user.save()
        mentor.user.save()
    reservation.save()
    messages.success(request, "Reservation Updated")
    return redirect(reverse("reservations:detail", kwargs={"pk": reservation.pk}))
    # return redirect(reverse("reservations:list", kwargs={"pk": reservation.pk}))

class ReservationListView(ListView):

    paginate_by = 10
    # paginate_orphans = 5
    context_object_name = "reservations"
    
    def get_queryset(self):
        
        user = self.request.user
        
        if user.is_mentor:
            qs = models.Reservation.objects.filter(mentor__user=user)
        else:
            qs = models.Reservation.objects.filter(user=user)
        return qs

templates/reservations/detail.html
{% extends "base.html" %}

{% block page_title %}
    Reservation {{reservatoin.check_in}}
{% endblock page_title %}
    
{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">       

        <div class="flex flex-col items-start border-l border-r border-t border-b">
            <div class="font-medium border-b py-8 px-5 w-full">
                {{reservation.check_in}} - {{reservation.check_out}} <span class="ml-5 {% if reservation.status == 'pending' %} text-yellow-500 {% elif reservation.status == 'canceled' %} text-red-600 {% else %} text-teal-600 {% endif %}">{{reservation.get_status_display}}</span>
            </div>

            <span class="text-2xl border-b p-5 mt-2 w-full">
                멘토 : {{reservation.mentor.user.name}} - 멘티 : {{reservation.user.name}}
            </span>

            <div class="flex p-5 border-b w-full">
                <div class="flex flex-col items-center">
                    {% include "mixins/user_avatar.html" with user=reservation.Mentor.user %}
                    <span class="mt-2 text-gray-500">{{reservation.Mentor.user.first_name}}</span>
                </div>
                <div class="ml-5 SAM">                    
                    <a href="{% url 'conversations:go' reservation.user.pk reservation.mentor.pk %}" class="leading-loose text-2xl font-medium text-teal-500">Send a Message</a>
                    <br>                
                    
                </div>
            </div>
            <div class="h-24 py-5 px-5 w-full text-right">
            {% if reservation.status == 'pending' %}
                {% if reservation.mentor.user == user %}
                    <a href="{% url 'reservations:edit' reservation.pk 'confirm' %}" class="SAM2 bg-green-500 btn-link p-5 text-white rounded-xl px-3 mb-5">Confirm Reservation</a>
                {% endif %}
                <a href="{% url 'reservations:edit' reservation.pk 'cancel' %}" class="SAM2 bg-red-500 btn-link p-5 text-white rounded-xl text-right">Cancel Reservation</a>
            {% endif %}
            </div>            
        </div>
        {% if request.user.is_mentor == False %}
        <div class="leading-loose max-w-xl m-4 p-10 bg-white rounded shadow-xl my-4 mx-auto">
            {% if reservation.status != 'canceled' %}
                {% if reservation.status == 'confirmed' %}                        
                    <span class="font-medium text-2xl text-center w-full block mb-5">Write your review</span>
                    <form action="{% url 'reviews:create' reservation.mentor.pk %}" method="POST" class="w-full mx-auto">
                        {% csrf_token %}
                        {{form}}
                        <div class ="text-center">
                            <button class="btn-link h-12 text-white w-32 mt-5 bg-green-500 rounded-lg">Submit Review</button>
                        </div>
                    </form>
                {% endif %}                            
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock content %}

templates/reservations/reservation_list.html
{% extends "base.html" %}
{% load static %}
{% block page_title %}
Reservation {{reservatoin.check_in}}
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<div class = "justify-self-auto">
{% for reservation in reservations %}
    <div class="relative flex flex-col items-center justify-center ">
        <div class="grid mt-8  gap-8 grid-cols-1">
            <div class="flex flex-col">
                <div class="bg-white shadow-md  rounded-3xl p-4">
                    <div class="flex-none lg:flex">
                        <div class=" h-full w-full lg:h-48 lg:w-48   lg:mb-0 mb-3">
                        
                            {% if reservation.mentor.user.image  %}
                            <img class="mx-auto h-40 rounded  object-cover object-center mb-6"
                            src="{{reservation.mentor.user.image.url}}" alt="content">
                            {% else %}                
                            <img class="h-40 rounded w-full object-cover object-center mb-6"
                            src="{% static 'img/no.png' %}" alt="content">
                            {% endif %}
                        
                        </div>
                        <div class="flex-auto ml-3 justify-evenly py-2">
                            <div class="flex flex-wrap ">
                                <div class="w-full flex-none text-xs text-blue-700 font-medium ">
                                    #{{reservation.status}}
                                </div>
                                <h2 class="flex-auto text-lg font-medium">멘티 : {{reservation.user.name}} - 멘토 :
                                    {{reservation.mentor.user.name}}</h2>
                            </div>
                            <p class="mt-3"></p>
                            <div class="flex py-4  text-sm text-gray-600">

                                <div class="flex-1 inline-flex items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none"
                                        viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                            d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                    </svg>
                                    <p class="">기간 : {{reservation.check_in}} ~ {{reservation.check_out}}</p>
                                </div>
                            </div>
                            <div class="flex p-4 pb-2 border-t border-gray-200 "></div>
                            <div class="text-right SAM2 text-sm font-medium">
                                <a class="mb-2 md:mb-0 bg-gray-900 px-5 py-2 shadow-sm tracking-wider text-white rounded-full hover:bg-gray-800"
                                    href="{% url 'reservations:detail' reservation.pk %}">this reservation</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
    <div class="flex items-center justify-center mx-auto mt-5 container">
        {% if page_obj.has_previous %}
            <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                <i class="fas fa-arrow-left fa-lg"></i>
            </a>
        {% endif %}
        <span class="mx-3 font-medium text-lg">
        Page{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
        {% if page_obj.has_next %}
            <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                <i class="fas fa-arrow-right fa-lg"></i>
            </a>
        {% endif %}
    </div>
</div>


{% endblock content %}