config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("wishlists/", include("wishlists.urls", namespace="wishlists")),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("search_mentor", views.search_mentor, name="search_mentor"),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("create/<int:mentor>/", views.create_review, name="create"),
    path("update/<int:pk>/", views.Update_review.as_view(), name="update"),
    path("remove/<int:pk>/", views.remove_review, name="remove"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
namespace = "users"
urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),  # login을 위한 url
    path("logout", views.log_out, name="logout"),  # logout을 위한 url
    path("signup", views.SignUpView.as_view(), name="signup"),  # signup를 위한 url
    path(
        "socialsignup", views.SocialSignUpView.as_view(), name="socialsignup"
    ),  # social signup을 위한 url
    path(
        "verify/<str:key>", views.complete_verification, name="complete-verification"
    ),  # 이메일 인증을 위한 url
    path("Mentor/<int:pk>/", views.MentorDetail.as_view(), name="detail"),
    path(
        "Mentor-profile/<int:pk>/",
        views.MentorProfileView.as_view(),
        name="mentor-profile",
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path(
        "update-mentor-profile/",
        views.UpdateMentorProfileView.as_view(),
        name="mentor-update",
    ),
    path("point/", views.UserPointView.as_view(), name="point"),
    path("point/add/", views.ajax_buy_point, name="buy_point"),
    path(
        "update-mentor-profile/",
        views.UpdateMentorProfileView.as_view(),
        name="mentor-update",
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path(
        "sms_verfy/",
        views.ajax_sms_verfy,
        name="sms_verfy",
    ),
    path(
        "sms_check/",
        views.ajax_sms_check,
        name="sms_check",
    ),
    path("Mentorsignup/", views.MentorSignUpView.as_view(), name="Mentorsignup"),
    path("Mentorsignup/kakaomap", views.renderkakaomap),
    path("Mentor-list/", views.MentorListView.as_view(), name="MentorList"),
    path("manage/", views.ManageUserView.as_view(), name="manage"),
    path("manage/submit", views.manage_user, name="submit"),
    path("kakao/login/callback/", views.kakao_callback, name="kakao-callback"),
    path("kakao/signup", views.KakaoSignUpView.as_view(), name="kakaosignup"),
    path("kakaologin",views.KakaoLoginTest.as_view(), name = "kakaologin"),
]

wishlists/urls.py
from django.urls import path
from . import views
app_name = "wishlists"

urlpatterns = [
    path("toggle/<int:mentor_pk>/", views.toggle_mentor , name="toggle-mentor"),
    path("favs/", views.SeeFavsView.as_view() , name="see-favs")
]

users/models.py
import uuid
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.conf import settings
from django.shortcuts import reverse
from core import models as core_models
from users import models as user_models
from core import managers as core_managers
from cal import Calendar

# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, email, name, gender, birthdate, phone_number, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            username=email,
            email=email,
            name=name,
            gender=gender,
            birthdate=birthdate,
            phone_number=phone_number,
            point=0,
            is_mentor=False,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, gender, birthdate, password):
        user = self.create_user(
            username=email,
            email=email,
            name=name,
            gender=gender,
            birthdate=birthdate,
            point=0,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OTHER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OTHER, "Other"),
    )
    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    image = models.ImageField(upload_to="images", blank=True, null=True) # 업로드 폴더 지정 후 사용할 예정
    name = models.CharField(max_length=10, blank=True)
    birthdate = models.DateField(
        auto_now=False, blank=True, null=True
    )  # 관리자 계정 생성후엔 auto_now_add=False로 바꿔줍시다
    gender = models.CharField(
        choices=GENDER_CHOICES, max_length=10, blank=True, default=GENDER_MALE
    )
    fake_users = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    email_secret = models.CharField(max_length=20, default="", blank=True)
    login_method = models.CharField(
        max_length=50, choices=LOGIN_CHOICES, default=LOGIN_EMAIL
    )
    phone_number = models.CharField(
        verbose_name="휴대폰 번호",
        max_length=11,
    )
    is_mentor = models.BooleanField(default=False)
    point = models.IntegerField(default=0)
    # objects = UserManager()
    # objects = core_managers.CustomModelManager()

    def verify_email(self):
        if self.email_verified is False:
            secret = uuid.uuid4().hex[:20]
            self.email_secret = secret
            html_message = render_to_string(
                "emails/verify_email.html", {"secret": secret}
            )
            send_mail(
                "Verify Airbnb Account",
                strip_tags(html_message),
                settings.EMAIL_FROM,
                [self.email],
                fail_silently=False,
                html_message=html_message,
            )
            self.save()
        return

    def __str__(self):
        return self.name


class Mentor(core_models.TimeStampedModel):
    user = models.ForeignKey(
        "users.User", related_name="mentor", on_delete=models.CASCADE
    )
    main_branch = models.ForeignKey(
        "users.MainBranch", related_name="mentor", on_delete=models.SET_NULL, null=True
    )
    sub_branch = models.ForeignKey(
        "users.SubBranch", related_name="mentor", on_delete=models.SET_NULL, null=True
    )
    company = models.CharField(max_length=50)
    department = models.CharField(max_length=50)
    career = models.TextField()
    is_authorized = models.BooleanField(default=False)
    is_supermento = models.BooleanField(default=False)
    objects = core_managers.CustomModelManager()
    address = models.CharField(max_length=256)
    address_name = models.CharField(max_length=256)

    def get_address_name(self):
        return self.address_name
    def get_address(self):
        return self.address    
    def __str__(self):
        return self.user.name

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        cnt = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                if review.review != "삭제된 메시지입니다":
                    all_ratings += review.score
                    cnt += 1
            if all_ratings != 0:
                return round(all_ratings / cnt, 2)
        return 0

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]


class MainBranch(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class SubBranch(models.Model):
    name = models.CharField(max_length=50)
    main_branch = models.ForeignKey(
        "users.MainBranch", related_name="sub_branch", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name + "(" + self.main_branch.name + ")"

    def get_name(self):
        return self.name


class Point(models.Model):
    """ List Model Definition """

    STATE_USE = "사용"
    STATE_PENDING = "보류중"
    STATE_CANCLED = "취소"
    STATE_ACCRUAL = "적립"
    STATE_WITHDRAW = "인출"
    STATEMENT_SET = (
        (STATE_USE, "사용"),
        (STATE_PENDING, "보류중"),
        (STATE_CANCLED, "취소"),
        (STATE_ACCRUAL, "적립"),
        (STATE_WITHDRAW, "인출"),
    )
    state = models.CharField(choices=STATEMENT_SET, max_length=40)
    product_name = models.CharField(max_length=40)
    date = models.DateTimeField()
    value = models.IntegerField(default=0)
    user = models.ForeignKey(
        "users.User", related_name="Point_Record", on_delete=models.CASCADE
    )

templates/users/Mentorsignup.html
{% extends "base.html" %}

{% block page_title %}
Sign Up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
<form method="POST" action="{% url "users:Mentorsignup" %}" class ="leading-loose max-w-xl m-4 p-10 bg-white rounded shadow-xl my-4 mx-auto">
    {% csrf_token %}    
    {{form.as_p}}
    <p id="openkakaomap" onclick="popup();" class = "inline-block"><i class="tlqkf fa fa-search">지도열어서 주소입력하기</i>&emsp;</p><br>    
    <div class ="center-0">
    <button id = "mentor_sign_up" type="submit" class ="center border rounded-lg text-white bg-green-500">Mentor Sign up</button>
    </div>
    
</form>

{% csrf_token %}
<script>
    var address = document.getElementById('id_address')
    var address_name = document.getElementById('id_address_name')
    var btn_submit = document.getElementById("mentor_sign_up")
    
    document.getElementById('address').readOnly = true;
    document.getElementById('address_name').readOnly = true;
    function popup() {
        var url = "http://"+location.host + "/users/Mentorsignup/kakaomap";
        var name = "Mentors 주소 입력창";
        var option = "width = 500, height = 500, top = 100, left = 200, location = no"
        window.open(url, name, option);
        return false;
    }
    function button_check(){
        return false;
    }
</script>

{% endblock content %}

templates/users/login.html
{% extends "base.html" %}
{% load socialaccount %}
{% load static %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <section class="min-h-screen flex flex-col ">
    <div class="flex flex-1 items-center justify-center">
        <div class="rounded-lg sm:border-2 px-4 lg:px-24 py-16 lg:max-w-xl sm:max-w-md w-full text-center">
            <form class="text-center" method="POST" action="{% url "users:login" %}">
                <h1 class="font-bold tracking-wider text-3xl mb-8 w-full text-gray-600">
                    Log in
                </h1>
                {% csrf_token %}
                {% for f in form %}
                {{f}} 
                {% endfor %}
                <div class="py-2">
                    <button type="submit" class="border-2 border-gray-100 focus:outline-none bg-purple-600 text-white font-bold tracking-wider block w-full p-2 rounded-lg focus:border-gray-700 hover:bg-purple-700">
                        Log In
                    </button>
                </div>
            </form>
            <div class="text-center mt-12">
                <span>
                    Don't have an account?
                </span>
                <a href="{% url "users:signup" %}"
                    class="font-light text-md text-indigo-600 underline font-semibold hover:text-indigo-800">Create
                    One</a>
            </div>
            <hr class="m-2">                   
            <div>            
                <a class="shadow-md m-2 h-full inline-block rounded-sm" href="{% url "users:kakaologin" %}">
                <img class= "inline-block"  src="{% static 'img/kakaoLogo.png' %}" alt="kakaoLogo" />                    
                </a>
                <a class="shadow-md m-2 h-full inline-block rounded-sm" href="{% provider_login_url 'google' %}">
                    <img class= "inline-block" src="{% static 'img/googleLogo.png' %}" alt="GoogleLogo" />  
                </a>
                {% comment %} <a class="shadow-md m-2 h-full inline-block rounded-sm" href="{% provider_login_url 'facebook' %}">
                    <img class= "inline-block" src="{% static 'img/FacebookLogo.png' %}" alt="FacebookLogo" />  
                </a> {% endcomment %}
                <a class="shadow-md m-2 h-full inline-block rounded-sm" href="{% provider_login_url 'naver' %}">
                <img class= "inline-block" src="{% static 'img/naverLogo.png' %}" alt="NaverLogo" />                    
                </a>
            </div>
        </div>
    </div>
   
</section>
{% endblock content %}

templates/users/manage_users.html
{% extends 'base.html' %}

{% block page_title %}
    회원 관리
{% endblock page_title %}
{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 w-full mx-auto overflow-auto">

        <div class="mb-5 flex flex-col justify-center md:flex-row md:justify-between items-center">
            <div class="flex w-full md:w-auto">
                <a href="{% url 'users:manage' %}?checked=false" class="w-full mr-2">
                    <div class="duration-300 shadow-md bg-red-500 text-white rounded-full w-full md:w-24 h-8 flex justify-center items-center hover:bg-red-600 hover:shadow-lg transform scale-95 hover:scale-100">미승인</div>
                </a>
                <a href="{% url 'users:manage' %}?checked=true" class="w-full">
                    <div class="duration-300 shadow-md bg-green-500 text-white rounded-full w-full md:w-24 h-8 flex justify-center items-center hover:bg-green-600 hover:shadow-lg transform scale-95 hover:scale-100">승인</div>
                </a>
            </div>

            <div class="mt-5 md:mt-0 w-full">
                <form id="search" method="GET" action="{% url 'users:manage' %}">
                    <div class="flex justify-end">
                        <input class="duration-300 rounded-full mr-2 border border-gray-400 hover:shadow-md focus:outline-none focus:border-indigo-500 text-sm px-4 w-full md:w-48 h-8 transform scale-95" placeholder="Search Name" type="text" name="search">
                        <button class="duration-300 inline-flex text-white bg-indigo-500 py-2 px-4 focus:outline-none hover:bg-indigo-700 rounded-full h-8 transform scale-95 hover:scale-100 hover:shadow-md">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    
    <form action="{% url 'users:submit' %}" method="POST">
    {% csrf_token %}
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            {% comment %} <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-l-md rounded-br"></th> {% endcomment %}
            <th class="px-2 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 text-center rounded-l-md rounded-br">이름</th>
            <th class="px-2 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 text-center">분야</th>
            <th class="px-2 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 text-center">경력</th>
            <th class="px-2 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 flex justify-center items-center rounded-r-md rounded-br">승인
              <input class="w-4 h-4 ml-1" type="checkbox" name="checkedbox_all" />
            </th>
            {% comment %} <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-200 rounded-r-md rounded-br"></th> {% endcomment %}
          </tr>
        </thead>

        <tbody>
        {% for mentor in Mentors %}
          <tr class="duration-300 border-b border-gray-300 hover:bg-gray-100">
            <td class="px-2 py-3 text-center">
                <a href="{% url 'users:profile' pk=mentor.pk %}" class="duration-300 hover:text-indigo-600 hover:underline">{{mentor.user.name}}</a>
            </td>
            <td class="px-2 py-3 text-center">{{mentor.main_branch}}/{{mentor.sub_branch}}</td>
            <td class="px-2 py-3 text-center">{{mentor.career}}</td>
            <td class="px-2 py-3 text-lg text-center text-gray-900">
                <input type="hidden" value="{{mentor.pk}}" name="mentor_pk" />
                <input class="w-4 h-4" 
                    type="checkbox" 
                    value="{{mentor.pk}}" 
                    name="checkedbox" {% if mentor.is_authorized %}checked{% endif %} />
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="flex pl-4 mt-4 lg:w-2/3 w-full mx-auto">
      <a href="{% url 'users:manage' %}"
        class="duration-300 text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0 hover:text-indigo-700">전체 보기
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      <button class="duration-300 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded hover:shadow-md">적용</button>
    </div>
    
    </form>
  </div>
</section>

<script>
var all_CheckBox;
var total_CheckBox;

$( document ).ready( function() {
  all_CheckBox = $("[name=checkedbox_all]");
  total_CheckBox = $("[name=checkedbox]");
  Check();

  all_CheckBox.click(function(){
    AllCheck();
  });

  total_CheckBox.click(function(){
    Check();
  });

});

function AllCheck(){
  if(all_CheckBox[0].checked){
    total_CheckBox.prop("checked", true);
  }else{
    total_CheckBox.prop("checked", false);
  }
}

function Check(){
  for(let i=0; i<total_CheckBox.length; i++){
    if(!total_CheckBox[i].checked){
      all_CheckBox.prop("checked", false);
      break;
    }else{
      all_CheckBox.prop("checked", true);
    }
  }
}

</script>

{% endblock content %}

templates/users/mentor_detail.html
{% extends "base.html" %}
{% load is_booked on_favs %}


{% block page_title %} {{Mentor.name}} {% endblock page_title %}
{% block content %}
{% if user.is_authenticated %}
<div class="container mx-auto flex justify-around pb-30">
    <div class="w-1/2">
        <div class="flex justify-between items-center">

            <div class="mb-5">
                <h4 class="text-3xl font-medium mb-px">{{Mentor.user.name}}</h4>
                
            </div>
            {% on_favs Mentor as on_favs_boolean %}
                {% if on_favs_boolean %}
                <a class="block mb-5 w-1/3 text-teal-600 font-bold"
                    href="{% url 'wishlists:toggle-mentor' Mentor.pk %}?action=remove">Remove from Favorite</a>
                {% else %}
                <a class="block mb-5 w-1/3 text-teal-600 font-bold"
                    href="{% url 'wishlists:toggle-mentor' Mentor.pk %}?action=add">Save to Favorite</a>
                {% endif %}      
            {% comment %} 멘토의 프로필로 가게 a태그 {% endcomment %}
            {% comment %} <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">
                {% include "mixins/user_avatar.html" with user=room.host %}
                <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
            </a> {% endcomment %}
        </div> 
        <div class="flex border-section">
            <span class="mr-5 font-light">{{Mentor.main_branch}}</span>
            <span class="mr-5 font-light">{{Mentor.sub_branch.get_name}}</span>
            <span class="mr-5 font-light">{{Mentor.company}}</span>
            <span class="mr-5 font-light">{{Mentor.department}}</span>            
        </div>
        <p class="border-b border-gray-400 pb-8 mt-8">
            {{room.description}}
        </p>
        <div class="crstyle border-b border-gray-400 pb-8 mt-8">
            <h4 id="amenities" class="font-medium text-lg mb-5">Career</h4>
            <li class="mb-2">{{Mentor.career}}</li>
        </div>

        {% comment %} 지도 썅려나 {% endcomment %}
        <div class="border-b border-gray-400 pb-8 mt-8">
        <h4 class="font-medium text-lg mb-5">Adress</h4><br>
        <h5 id= "mentor_address_name">{{Mentor.address_name}}</h5><br>
        <h5 id= "mentor_address">{{Mentor.address}} </h5>
        <div id="map" class = "pb-8 mt-8 maph"></div>
        </div>
        <div class="mt-10">
            <h4 class="font-medium text-2xl mb-5">Reviews</h4>
            <div class="flex items-center">    
                <div>
                    <i class="fas fa-star text-teal-500"></i>
                    <span class="font-bold text-xl">{{Mentor.total_rating}}</span>
                </div>
                <div class="h-4 w-px bg-gray-400 mx-5"></div>
                <div>
                    <span class="font-bold text-xl">{{Mentor.reviews.count}}</span>
                    <span>review{{Mentor.reviews.count|pluralize}}</span>
                </div>              
            </div>
            <br>
             <div class="bg-white dark:bg-gray-800 w-full rounded-lg p-4 mb-6 shadow sm:inline-block">
                <div class="flex items-start text-left">
                    {% for review in Mentor.reviews.all %}
                    <div class="ml-6">
                        <p class="flex items-baseline">
                            <span class="text-gray-600 dark:text-gray-200 font-bold">
                                {{review.user.name}}
                            </span>
                            <span class="text-gray-500 dark:text-gray-300  ml-2 text-sm">
                                {{review.created|date:"F Y"}}
                            </span>
                        </p>
                        {% if review.review != "삭제된 메시지입니다" %}
                        <div class="flex items-center mt-1">
                            <i class="fas fa-star text-teal-500"></i>
                            {{review.score}}
                        </div>
                        {% endif %}

                        <div class="mt-3">
                            <p class="rhdqor mt-1 max-w-xs dark:text-white">
                                {% if review.review == "삭제된 메시지입니다" %}
                            <p><del>{{review.review}}</del>
                            <p>
                                {% else %}
                            <p>{{review.review}}</p>
                            <div class = "mt-4 h-8">
                                <a class = "bg-green-500 rounded-lg text-white" href="{% url 'reviews:update' pk=review.pk %}">update</a>
                                <a class = "bg-red-500 rounded-lg text-white" href="{% url 'reviews:remove' pk=review.pk %}">remove</a>
                            </div>
                            {% endif %}
                            </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <div class="w-1/3">
        {% for calendar in Mentor.get_calendars %}
        <div class="mb-20">
            <span class="text-center font-semibold text-lg block mb-8">{{calendar.get_month}} /
                {{calendar.year}}</span>
            <div class="grid grid-cols-7 gap-10 mb-4">
                {% for day in calendar.day_names %}
                <span>{{day}}</span>
                {% endfor %}
            </div>
            <div class="grid grid-cols-7 gap-5">
                {% for day in calendar.get_days %}
                    {% is_booked request.user Mentor day as is_booked_bool %}
                    {% if day.number != 0 %}
                    {% if day.past %}
                    <span class="rounded bg-gray-200 w-full text-center p-1 text-gray-300">{{day}}</span>
                    {% elif is_booked_bool %}
                    <a href="{% url 'reservations:create' Mentor.pk day.year day.month day.number %}"
                        class="bg-gray-200 w-full text-center rounded text-indigo-300 p-1 hover:bg-teal-400 hover:font-medium hover:text-white cursor-pointer line-through">{{day}}</a>
                    {% else %}
                        <a href="{% url 'reservations:create' Mentor.pk day.year day.month day.number %}"
                        class="bg-gray-200 w-full text-center rounded text-gray-700 p-1 hover:bg-teal-400 hover:font-medium hover:text-white cursor-pointer" onclick="checkPoint()">{{day}}</a>
                    {% endif %}
                    {% else %}
                    <span></span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <script type="text/javascript">
    window.location.href='{% url "users:login" %}'
    </script>
{% endif %}
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d4770735569ace7ccb42af3fc64320ab&libraries=services"></script>
<script>
var address = document.getElementById("mentor_address").textContent;
var address_name = document.getElementById("mentor_address_name").textContent;
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = {
        center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
        level: 3 // 지도의 확대 레벨
    };  

// 지도를 생성합니다    
var map = new kakao.maps.Map(mapContainer, mapOption); 

// 주소-좌표 변환 객체를 생성합니다
var geocoder = new kakao.maps.services.Geocoder();

// 주소로 좌표를 검색합니다
geocoder.addressSearch(address, function(result, status) {

    // 정상적으로 검색이 완료됐으면 
     if (status === kakao.maps.services.Status.OK) {

        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

        // 결과값으로 받은 위치를 마커로 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            position: coords
        });

        // 인포윈도우로 장소에 대한 설명을 표시합니다
        var infowindow = new kakao.maps.InfoWindow({
            content: `<div style="width:150px;text-align:center;padding:6px 0;">${address_name}</div>`
        });
        infowindow.open(map, marker);

        // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
        map.setCenter(coords);
    } 
});    
</script>

<script>
function checkPoint(){
    var point = "{{request.user.point}}"
    if(point < 20){
        alert("포인트가 부족합니다.\n현재 포인트 : " + point);
        event.preventDefault();
        return;
    }

    if(!confirm("예약하시겠습니까?\n포인트 : " + point + " → " + (parseInt(point) - 20).toString() )){
        event.preventDefault();
        return; 
    }
}
</script>
{% endblock content %}

templates/users/socialsignup.html
{% extends "base.html" %}

{% block page_title %}
    Social Sign up
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    {% include 'partials/social_login.html' %}

    <form method="POST" action="{% url "users:socialsignup" %}">
        {% csrf_token %}
        {{form.as_p}}
        <button>Social Sign up</button>
    </form>
{% endblock content %}

templates/users/update_mentor_profile.html
{% extends "base.html" %}

{% block page_title %}
    Update Mentor Profile
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="leading-loose max-w-xl m-4 p-10 bg-white rounded shadow-xl my-4 mx-auto">       

        {% include 'mixins/auth/auth_form.html' with form=form cta="Update profile" %}
    </div>
{% endblock content %}